### ISSUE TITLE
Cancelling an already cancelled reservation

### ISSUE THREAD

**Issue by fft-ucd** [thiagohora/COMP47910-project#8]
Logged in as a Starwood member I have cancelled a reservation. If I go back to the page the Cancel button is still present. If I click it the following error is spewd:

Uncaught runtime errors:
×
ERROR
Request failed with status code 409
AxiosError: Request failed with status code 409
    at settle (webpack-internal:///./node_modules/axios/lib/core/settle.js:24:12)
    at XMLHttpRequest.onloadend (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:106:66)

**Comment by thiagohora** [comment]
Done
